### ISSUE TITLE
Linux or MacM1 Version?

### ISSUE THREAD

**Issue by ninjamar** [sserver224/OpenAI-Voice-Assistant#2]
Any support for linux or M1 Mac?

**Comment by sserver224** [comment]
No support. I don't have a Mac (or Linux).
Windows only stuff in my program:

- Loading settings (registry)
- "Computer, set volume to x" (uses WinMM DLL)
- "Computer, power off" or "Computer, restart" (uses shutdown.exe -s -t 0 and shutdown.exe -r -t 0 respectively)
- "Computer, get volume" (uses WinMM DLL)
- "Computer, lock" (uses rundll32.exe)
- Start and stop listening tones (uses winsound)
- Hold to wake (uses XInput)
- VM detection (uses keywords "Microsoft" and "Virtual" and uses WMI)

Tkinter is preinstalled in Windows and Mac only.

If you want a version for Linux, please commit the file converting the features above to Mac and Linux versions. Name it openai_voice_mac or openai_voice_linux if committed as a seperate file. If you don't want a file per platform, modify the existing code with platform auto detection (some modules will fail to import or attempt to load something Windows specific which will result in a crash if run on non-Windows). Soundflower detection for is_voicemeeter() is highly appreciated for Mac mode (or if using seperate files, the script for Mac)!

**Comment by ninjamar** [comment]
I don't have time to implement this

**Comment by sserver224** [comment]
> I don't have time to implement this

Sorry, then no cross platform support then
